services:
  app:
    image: mysociety/housing_data_exploration:${TAG:-latest}
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./:/workspaces/housing_data_exploration/