FROM ghcr.io/mysociety/data_co

# Make an empty project directory so the 'self' setup doesn't fail and scripts can be setup
# Override the .pth created at previous stages to point to where the working directory will land
COPY pyproject.toml poetry.lock /setup/ 
COPY src/data_common/pyproject.toml src/data_common/poetry.lock /setup/src/data_common/
RUN mkdir /setup/src/housing_data_exploration && touch /setup/src/housing_data_exploration/__init__.py \
    && touch /setup/src/data_common/__init__.py \
    && export PATH="$HOME/.poetry/bin:$PATH" \
    && cd /setup/ && poetry install \
    && echo "/workspaces/housing_data_exploration/src/" > /usr/local/lib/python3.10/site-packages/housing_data_exploration.pth \
    && echo "/workspaces/housing_data_exploration/src/data_common/src" > /usr/local/lib/python3.10/site-packages/data_common.pth
